[package]
name = "playground"
version = "0.0.1"
authors = ["The Rust Playground"]

[dependencies]
advapi32-sys = "0.2.0"
aho-corasick = "0.6.3"
ansi_term = "0.9.0"
atty = "0.2.2"
base64 = "0.6.0"
bitflags = "0.9.1"
byteorder = "1.1.0"
bytes = "0.4.4"
cfg-if = "0.1.2"
chrono = "0.4.0"
clap = "2.26.0"
cmake = "0.1.24"
conv = "0.3.3"
cookie = "0.9.1"
crossbeam = "0.3.0"
custom_derive = "0.1.7"
docopt = "0.8.1"
dtoa = "0.4.1"
either = "1.1.0"
env_logger = "0.4.3"
extprim = "1.4.0"
flate2 = "0.2.19"
futures = "0.1.14"
futures-cpupool = "0.1.5"
gcc = "0.3.51"
gdi32-sys = "0.2.0"
getopts = "0.2.14"
glob = "0.2.11"
hpack = "0.3.0"
httparse = "1.2.3"
hyper = "0.11.2"
idna = "0.1.4"
iovec = "0.1.0"
itertools = "0.6.1"
itoa = "0.3.1"
kernel32-sys = "0.2.2"
language-tags = "0.2.2"
lazy_static = "0.2.8"
lazycell = "0.5.1"
libc = "0.2.29"
libz-sys = "1.0.16"
log = "0.3.8"
magenta = "0.1.1"
magenta-sys = "0.1.1"
matches = "0.1.6"
memchr = "1.0.1"
mime = "0.3.3"
miniz-sys = "0.1.9"
mio = "0.6.10"
miow = "0.2.1"
net2 = "0.2.31"
nix = "0.9.0"
nom = "3.2.0"
num = "0.1.40"
num-bigint = "0.1.40"
num-complex = "0.1.40"
num-integer = "0.1.35"
num-iter = "0.1.34"
num-rational = "0.1.39"
num-traits = "0.1.40"
num_cpus = "1.6.2"
percent-encoding = "1.0.0"
pkg-config = "0.3.9"
quick-error = "1.2.0"
quote = "0.3.15"
rand = "0.3.16"
regex = "0.2.2"
regex-syntax = "0.4.1"
rustc-serialize = "0.3.24"
rustc_version = "0.2.1"
safemem = "0.2.0"
scoped-tls = "0.1.0"
semver = "0.7.0"
semver-parser = "0.7.0"
serde = "1.0.11"
serde_codegen = "0.9.0"
serde_codegen_internals = "0.14.2"
serde_derive = "1.0.11"
serde_derive_internals = "0.15.1"
serde_json = "1.0.2"
slab = "0.4.0"
smallvec = "0.2.1"
solicit = "0.4.4"
strsim = "0.6.0"
syn = "0.11.11"
synom = "0.11.3"
syntex = "0.58.1"
syntex_errors = "0.59.1"
syntex_pos = "0.59.1"
syntex_syntax = "0.59.1"
take = "0.1.0"
tempdir = "0.3.5"
term = "0.4.6"
term_size = "0.3.0"
textwrap = "0.7.0"
thread-id = "3.2.0"
thread_local = "0.3.4"
time = "0.1.38"
tokio-core = "0.1.9"
tokio-io = "0.1.2"
tokio-proto = "0.1.1"
tokio-service = "0.1.0"
toml = "0.4.4"
traitobject = "0.1.0"
typeable = "0.1.2"
unicase = "2.0.0"
unicode-bidi = "0.3.4"
unicode-normalization = "0.1.5"
unicode-segmentation = "1.2.0"
unicode-width = "0.1.4"
unicode-xid = "0.1.0"
unreachable = "1.0.0"
url = "1.5.1"
user32-sys = "0.2.0"
utf8-ranges = "1.0.0"
uuid = "0.5.1"
vcpkg = "0.2.2"
vec_map = "0.8.0"
void = "1.0.2"
winapi = "0.2.8"
winapi-build = "0.1.1"
ws2_32-sys = "0.2.1"
xml-rs = "0.6.1"
