[dependencies]
advapi32-sys = "0.2.0"
aho-corasick = "0.6.2"
ansi_term = "0.9.0"
bitflags = "0.7.0"
byteorder = "1.0.0"
cfg-if = "0.1.0"
chrono = "0.3.0"
clap = "2.20.3"
cookie = "0.6.0"
crossbeam = "0.2.10"
docopt = "0.7.0"
dtoa = "0.4.1"
either = "1.0.2"
env_logger = "0.4.0"
flate2 = "0.2.17"
gcc = "0.3.43"
gdi32-sys = "0.2.0"
getopts = "0.2.14"
gl_generator = "0.5.2"
glob = "0.2.11"
hpack = "0.3.0"
httparse = "1.2.1"
hyper = "0.10.4"
idna = "0.1.0"
itertools = "0.5.9"
itoa = "0.3.1"
kernel32-sys = "0.2.2"
khronos_api = "1.0.0"
language-tags = "0.2.2"
lazy_static = "0.2.2"
lazycell = "0.4.0"
libc = "0.2.20"
libz-sys = "1.0.12"
log = "0.3.6"
matches = "0.1.4"
memchr = "1.0.1"
mime = "0.2.2"
miniz-sys = "0.1.9"
mio = "0.6.4"
miow = "0.2.0"
net2 = "0.2.26"
nix = "0.7.0"
nom = "2.1.0"
num = "0.1.36"
num-bigint = "0.1.35"
num-complex = "0.1.35"
num-integer = "0.1.32"
num-iter = "0.1.32"
num-rational = "0.1.35"
num-traits = "0.1.36"
num_cpus = "1.2.1"
phf = "0.7.21"
phf_generator = "0.7.21"
phf_shared = "0.7.21"
pkg-config = "0.3.9"
quote = "0.3.12"
rand = "0.3.15"
regex = "0.2.1"
regex-syntax = "0.4.0"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.22"
rustc_version = "0.1.7"
semver = "0.6.0"
semver-parser = "0.7.0"
serde = "0.9.6"
serde_codegen = "0.9.0"
serde_codegen_internals = "0.13.0"
serde_json = "0.9.5"
siphasher = "0.2.1"
slab = "0.3.0"
solicit = "0.4.4"
strsim = "0.6.0"
syn = "0.11.4"
syntex = "0.58.0"
syntex_errors = "0.58.0"
syntex_pos = "0.58.0"
syntex_syntax = "0.58.0"
tempdir = "0.3.5"
term = "0.4.5"
term_size = "0.2.2"
thread-id = "3.0.0"
thread_local = "0.3.2"
time = "0.1.36"
toml = "0.2.1"
traitobject = "0.1.0"
typeable = "0.1.2"
unicase = "1.4.0"
unicode-bidi = "0.2.4"
unicode-normalization = "0.1.4"
unicode-segmentation = "1.1.0"
unicode-width = "0.1.4"
unicode-xid = "0.0.4"
unreachable = "0.1.1"
url = "1.4.0"
user32-sys = "0.2.0"
utf8-ranges = "1.0.0"
uuid = "0.4.0"
vec_map = "0.6.0"
void = "1.0.2"
winapi = "0.2.8"
winapi-build = "0.1.1"
ws2_32-sys = "0.2.1"
xml-rs = "0.3.5"

[package]
authors = ["The Rust Playground"]
name = "playground"
version = "0.0.1"
