[package]
name = "playground"
version = "0.0.1"
authors = ["The Rust Playground"]
[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
incremental = false

[dependencies]
adler32 = "1.0.2"
advapi32-sys = "0.2.0"
aho-corasick = "0.6.4"
ansi_term = "0.10.2"
arrayvec = "0.4.7"
atty = "0.2.6"
backtrace = "0.3.5"
backtrace-sys = "0.1.16"
base64 = "0.9.0"
bit-set = "0.4.0"
bit-vec = "0.4.4"
bitflags = "1.0.1"
build_const = "0.2.0"
byteorder = "1.2.1"
bytes = "0.4.6"
cc = "1.0.4"
cfg-if = "0.1.2"
chrono = "0.4.0"
clap = "2.30.0"
cmake = "0.1.29"
color_quant = "1.0.0"
cookie = "0.10.1"
crc = "1.7.0"
crossbeam = "0.3.2"
crossbeam-deque = "0.2.0"
crossbeam-epoch = "0.3.0"
crossbeam-utils = "0.2.2"
csv = "1.0.0-beta.5"
csv-core = "0.1.4"
data-encoding = "2.1.1"
debug_unreachable = "0.1.1"
deflate = "0.7.17"
docopt = "0.8.3"
dtoa = "0.4.2"
either = "1.4.0"
encoding_rs = "0.7.2"
enum_primitive = "0.1.1"
env_logger = "0.5.4"
error-chain = "0.11.0"
extprim = "1.5.1"
filetime = "0.1.15"
fixedbitset = "0.1.8"
flate2 = "1.0.1"
foreign-types = "0.3.2"
foreign-types-shared = "0.1.1"
fuchsia-zircon = "0.3.3"
fuchsia-zircon-sys = "0.3.3"
futf = "0.1.3"
futures = "0.1.18"
futures-cpupool = "0.1.8"
gcc = "0.3.54"
getopts = "0.2.17"
gif = "0.9.2"
glob = "0.2.11"
hpack = "0.2.0"
html5ever = "0.18.0"
httparse = "1.2.4"
humantime = "1.1.1"
hyper = "0.11.21"
hyper-tls = "0.1.2"
idna = "0.1.4"
image = "0.18.0"
inflate = "0.3.4"
iovec = "0.1.2"
itertools = "0.7.6"
itoa = "0.3.4"
jpeg-decoder = "0.1.14"
kernel32-sys = "0.2.2"
language-tags = "0.2.2"
lazy_static = "1.0.0"
lazycell = "0.6.0"
libc = "0.2.37"
libflate = "0.1.14"
libz-sys = "1.0.18"
log = "0.4.1"
lzw = "0.10.0"
mac = "0.1.1"
markup5ever = "0.3.2"
matches = "0.1.6"
memchr = "2.0.1"
memmap = "0.6.2"
memoffset = "0.2.1"
mime = "0.3.5"
mime_guess = "2.0.0-alpha.4"
miniz-sys = "0.1.10"
mio = "0.6.13"
miow = "0.2.1"
native-tls = "0.1.5"
net2 = "0.2.32"
nix = "0.10.0"
nodrop = "0.1.12"
num = "0.1.42"
num-bigint = "0.1.43"
num-complex = "0.1.42"
num-integer = "0.1.36"
num-iter = "0.1.35"
num-rational = "0.1.42"
num-traits = "0.2.0"
num_cpus = "1.8.0"
ordermap = "0.3.5"
percent-encoding = "1.0.1"
petgraph = "0.4.11"
phf = "0.7.21"
phf_codegen = "0.7.21"
phf_generator = "0.7.21"
phf_shared = "0.7.21"
pkg-config = "0.3.9"
png = "0.11.0"
precomputed-hash = "0.1.1"
proc-macro2 = "0.2.3"
quick-error = "1.2.1"
quote = "0.4.2"
rand = "0.4.2"
rayon = "1.0.0"
rayon-core = "1.4.0"
regex = "0.2.6"
regex-syntax = "0.4.2"
relay = "0.1.1"
remove_dir_all = "0.3.0"
reqwest = "0.8.5"
ring = "0.13.0-alpha"
rustc-demangle = "0.1.7"
rustc-serialize = "0.3.24"
rustc_version = "0.2.2"
safemem = "0.2.0"
same-file = "1.0.2"
schannel = "0.1.10"
scoped-tls = "0.1.0"
scoped_threadpool = "0.1.9"
scopeguard = "0.3.3"
select = "0.4.2"
semver = "0.9.0"
semver-parser = "0.7.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_derive_internals = "0.19.0"
serde_json = "1.0.10"
serde_urlencoded = "0.5.1"
siphasher = "0.2.2"
slab = "0.4.0"
smallvec = "0.6.0"
solicit = "0.4.4"
string_cache = "0.6.2"
string_cache_codegen = "0.4.0"
string_cache_shared = "0.3.0"
strsim = "0.7.0"
syn = "0.12.13"
synom = "0.11.3"
syntex_errors = "0.59.1"
syntex_pos = "0.59.1"
syntex_syntax = "0.59.1"
syslog = "3.3.0"
take = "0.1.0"
tar = "0.4.14"
tempdir = "0.3.6"
tendril = "0.3.1"
term = "0.5.1"
term_size = "1.0.0-beta1"
termcolor = "0.3.5"
termion = "1.5.1"
textwrap = "0.9.0"
thread-id = "3.2.0"
thread_local = "0.3.5"
threadpool = "1.7.1"
time = "0.1.39"
tokio-core = "0.1.12"
tokio-io = "0.1.5"
tokio-proto = "0.1.1"
tokio-service = "0.1.0"
tokio-tls = "0.1.4"
toml = "0.4.5"
traitobject = "0.1.0"
typeable = "0.1.2"
unicase = "2.1.0"
unicode-bidi = "0.3.4"
unicode-normalization = "0.1.5"
unicode-segmentation = "1.2.0"
unicode-width = "0.1.4"
unicode-xid = "0.1.0"
unix_socket = "0.5.0"
unreachable = "1.0.0"
untrusted = "0.6.1"
url = "1.7.0"
utf-8 = "0.7.2"
utf8-ranges = "1.0.0"
uuid = "0.6.0"
vcpkg = "0.2.2"
vec_map = "0.8.0"
version_check = "0.1.3"
void = "1.0.2"
walkdir = "2.1.4"
winapi = "0.3.4"
winapi-build = "0.1.1"
winapi-i686-pc-windows-gnu = "0.4.0"
winapi-x86_64-pc-windows-gnu = "0.4.0"
wincolor = "0.1.6"
ws2_32-sys = "0.2.1"
xattr = "0.1.11"
xml-rs = "0.7.0"
