[package]
name = "playground"
version = "0.0.1"
authors = ["The Rust Playground"]

[dependencies]
advapi32-sys = "0.2.0"
aho-corasick = "0.6.3"
ansi_term = "0.9.0"
atty = "0.2.2"
base64 = "0.5.2"
bitflags = "0.8.2"
byteorder = "1.0.0"
cfg-if = "0.1.0"
chrono = "0.3.1"
clap = "2.24.2"
cmake = "0.1.23"
cookie = "0.8.1"
crossbeam = "0.2.10"
docopt = "0.7.0"
dtoa = "0.4.1"
either = "1.1.0"
env_logger = "0.4.2"
flate2 = "0.2.19"
gcc = "0.3.46"
gdi32-sys = "0.2.0"
getopts = "0.2.14"
glob = "0.2.11"
hpack = "0.3.0"
httparse = "1.2.2"
hyper = "0.10.10"
idna = "0.1.1"
itertools = "0.6.0"
itoa = "0.3.1"
kernel32-sys = "0.2.2"
language-tags = "0.2.2"
lazy_static = "0.2.8"
libc = "0.2.22"
libz-sys = "1.0.13"
log = "0.3.7"
matches = "0.1.4"
memchr = "1.0.1"
mime = "0.2.4"
miniz-sys = "0.1.9"
net2 = "0.2.29"
nix = "0.8.1"
nom = "3.0.0"
num = "0.1.37"
num-bigint = "0.1.37"
num-complex = "0.1.37"
num-integer = "0.1.34"
num-iter = "0.1.33"
num-rational = "0.1.36"
num-traits = "0.1.37"
num_cpus = "1.4.0"
pkg-config = "0.3.9"
quote = "0.3.15"
rand = "0.3.15"
regex = "0.2.1"
regex-syntax = "0.4.0"
rustc-serialize = "0.3.24"
rustc_version = "0.2.1"
semver = "0.6.0"
semver-parser = "0.7.0"
serde = "1.0.6"
serde_codegen = "0.9.0"
serde_codegen_internals = "0.14.2"
serde_derive = "1.0.6"
serde_derive_internals = "0.15.0"
serde_json = "1.0.2"
slab = "0.3.0"
solicit = "0.4.4"
strsim = "0.6.0"
syn = "0.11.11"
synom = "0.11.3"
syntex = "0.58.1"
syntex_errors = "0.58.1"
syntex_pos = "0.58.1"
syntex_syntax = "0.58.1"
tempdir = "0.3.5"
term = "0.4.5"
term_size = "0.3.0"
thread-id = "3.1.0"
thread_local = "0.3.3"
time = "0.1.37"
toml = "0.4.1"
traitobject = "0.1.0"
typeable = "0.1.2"
unicase = "2.0.0"
unicode-bidi = "0.3.0"
unicode-normalization = "0.1.4"
unicode-segmentation = "1.2.0"
unicode-width = "0.1.4"
unicode-xid = "0.1.0"
unreachable = "1.0.0"
url = "1.4.0"
user32-sys = "0.2.0"
utf8-ranges = "1.0.0"
uuid = "0.5.0"
vec_map = "0.8.0"
void = "1.0.2"
winapi = "0.2.8"
winapi-build = "0.1.1"
ws2_32-sys = "0.2.1"
xml-rs = "0.4.1"
