[package]
name = "playground"
version = "0.0.1"
authors = ["The Rust Playground"]
[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
incremental = false

[dependencies]
adler32 = "=1.0.3"
aho-corasick = "=0.6.5"
ansi_term = "=0.11.0"
arrayvec = "=0.4.7"
atty = "=0.2.10"
backtrace = "=0.3.9"
backtrace-sys = "=0.1.23"
base64 = "=0.9.2"
bit-set = "=0.4.0"
bit-vec = "=0.4.4"
bitflags = "=1.0.3"
build_const = "=0.2.1"
byteorder = "=1.2.3"
bytes = "=0.4.8"
cc = "=1.0.17"
cfg-if = "=0.1.4"
chrono = "=0.4.4"
clap = "=2.32.0"
cloudabi = "=0.0.3"
color_quant = "=1.0.1"
cookie = "=0.10.1"
crc = "=1.8.1"
crossbeam = "=0.3.2"
crossbeam-deque = "=0.3.1"
crossbeam-epoch = "=0.4.3"
crossbeam-utils = "=0.3.2"
csv = "=1.0.0"
csv-core = "=0.1.4"
data-encoding = "=2.1.1"
debug_unreachable = "=0.1.1"
deflate = "=0.7.18"
docopt = "=1.0.0"
dtoa = "=0.4.2"
either = "=1.5.0"
encoding_rs = "=0.7.2"
env_logger = "=0.5.10"
error-chain = "=0.12.0"
extprim = "=1.6.0"
filetime = "=0.2.1"
fixedbitset = "=0.1.9"
flate2 = "=1.0.1"
fnv = "=1.0.6"
foreign-types = "=0.3.2"
foreign-types-shared = "=0.1.1"
fuchsia-zircon = "=0.3.3"
fuchsia-zircon-sys = "=0.3.3"
futf = "=0.1.4"
futures = "=0.1.21"
futures-cpupool = "=0.1.8"
gcc = "=0.3.54"
getopts = "=0.2.17"
gif = "=0.10.0"
glob = "=0.2.11"
h2 = "=0.1.10"
html5ever = "=0.18.0"
http = "=0.1.7"
httparse = "=1.3.2"
humantime = "=1.1.1"
hyper = "=0.12.5"
hyper-tls = "=0.1.3"
idna = "=0.1.4"
image = "=0.19.0"
indexmap = "=1.0.1"
inflate = "=0.4.3"
iovec = "=0.1.2"
itertools = "=0.7.8"
itoa = "=0.4.1"
jpeg-decoder = "=0.1.15"
kernel32-sys = "=0.2.2"
language-tags = "=0.2.2"
lazy_static = "=1.0.1"
lazycell = "=1.0.0"
libc = "=0.2.42"
libflate = "=0.1.15"
libz-sys = "=1.0.18"
log = "=0.4.3"
lzw = "=0.10.0"
mac = "=0.1.1"
markup5ever = "=0.3.2"
matches = "=0.1.6"
memchr = "=2.0.1"
memmap = "=0.6.2"
memoffset = "=0.2.1"
mime = "=0.3.7"
mime_guess = "=2.0.0-alpha.5"
miniz-sys = "=0.1.10"
mio = "=0.6.14"
miow = "=0.2.1"
native-tls = "=0.1.5"
net2 = "=0.2.33"
new_debug_unreachable = "=1.0.1"
nodrop = "=0.1.12"
num = "=0.1.42"
num-bigint = "=0.2.0"
num-complex = "=0.2.0"
num-derive = "=0.2.2"
num-integer = "=0.1.39"
num-iter = "=0.1.37"
num-rational = "=0.2.1"
num-traits = "=0.2.5"
num_cpus = "=1.8.0"
ordermap = "=0.3.5"
percent-encoding = "=1.0.1"
petgraph = "=0.4.12"
phf = "=0.7.22"
phf_codegen = "=0.7.22"
phf_generator = "=0.7.22"
phf_shared = "=0.7.22"
pkg-config = "=0.3.11"
png = "=0.12.0"
precomputed-hash = "=0.1.1"
proc-macro2 = "=0.4.6"
quick-error = "=1.2.2"
quote = "=0.6.3"
rand = "=0.5.3"
rand_core = "=0.2.1"
rayon = "=1.0.1"
rayon-core = "=1.4.0"
regex = "=1.0.1"
regex-syntax = "=0.6.1"
relay = "=0.1.1"
remove_dir_all = "=0.5.1"
reqwest = "=0.8.6"
ring = "=0.12.1"
rustc-demangle = "=0.1.8"
rustc-serialize = "=0.3.24"
rustc_version = "=0.2.2"
safemem = "=0.2.0"
same-file = "=1.0.2"
schannel = "=0.1.13"
scoped-tls = "=0.1.2"
scoped_threadpool = "=0.1.9"
scopeguard = "=0.3.3"
select = "=0.4.2"
semver = "=0.9.0"
semver-parser = "=0.7.0"
serde = "=1.0.68"
serde_derive = "=1.0.68"
serde_derive_internals = "=0.23.1"
serde_json = "=1.0.22"
serde_urlencoded = "=0.5.2"
siphasher = "=0.2.2"
slab = "=0.4.0"
smallvec = "=0.6.2"
string = "=0.1.0"
string_cache = "=0.6.2"
string_cache_codegen = "=0.4.1"
string_cache_shared = "=0.3.0"
strsim = "=0.7.0"
synom = "=0.11.3"
syntex_errors = "=0.59.1"
syntex_pos = "=0.59.1"
syntex_syntax = "=0.59.1"
syslog = "=4.0.0"
take = "=0.1.0"
tar = "=0.4.16"
tempdir = "=0.3.7"
tendril = "=0.3.1"
term = "=0.5.1"
termcolor = "=0.3.6"
termion = "=1.5.1"
textwrap = "=0.10.0"
thread-id = "=3.3.0"
thread_local = "=0.3.5"
threadpool = "=1.7.1"
time = "=0.1.40"
tokio = "=0.1.7"
tokio-codec = "=0.1.0"
tokio-core = "=0.1.17"
tokio-executor = "=0.1.2"
tokio-fs = "=0.1.1"
tokio-io = "=0.1.7"
tokio-proto = "=0.1.1"
tokio-reactor = "=0.1.2"
tokio-service = "=0.1.0"
tokio-tcp = "=0.1.0"
tokio-threadpool = "=0.1.4"
tokio-timer = "=0.2.4"
tokio-tls = "=0.1.4"
tokio-udp = "=0.1.1"
toml = "=0.4.6"
traitobject = "=0.1.0"
try-lock = "=0.2.2"
typeable = "=0.1.2"
ucd-util = "=0.1.1"
unicase = "=2.1.0"
unicode-bidi = "=0.3.4"
unicode-normalization = "=0.1.7"
unicode-segmentation = "=1.2.1"
unicode-width = "=0.1.5"
unicode-xid = "=0.1.0"
unix_socket = "=0.5.0"
unreachable = "=1.0.0"
untrusted = "=0.5.1"
url = "=1.7.0"
utf-8 = "=0.7.2"
utf8-ranges = "=1.0.0"
vcpkg = "=0.2.4"
vec_map = "=0.8.1"
version_check = "=0.1.3"
void = "=1.0.2"
walkdir = "=2.1.4"
want = "=0.0.5"
winapi = "=0.3.5"
winapi-build = "=0.1.1"
winapi-i686-pc-windows-gnu = "=0.4.0"
winapi-x86_64-pc-windows-gnu = "=0.4.0"
wincolor = "=0.1.6"
ws2_32-sys = "=0.2.1"
xattr = "=0.2.1"

[dependencies.syn]
version = "=0.14.2"
features = ["extra-traits", "fold", "full", "visit", "visit-mut"]

[dependencies.uuid]
version = "=0.6.5"
features = ["serde", "u128", "v1", "v3", "v4", "v5"]
