[package]
authors = ["Jake Goulding <jake.goulding@integer32.com>"]
name = "top-crates"
version = "0.1.0"

[dependencies]
cargo = "0.16"
hyper = "0.10.4"
hyper-native-tls = "0.2.2"
lazy_static = "0.2"
serde = "0.9.6"
serde_derive = "0.9.6"
serde_json = "0.9.5"
toml = "0.3.0"
