[package]
authors = ["Jake Goulding <jake.goulding@integer32.com>"]
name = "top-crates"
version = "0.1.0"

[dependencies]
cargo = "0.26.0"
lazy_static = "1.0.0"
reqwest = "0.8.0"
serde = "1.0.1"
serde_derive = "1.0.1"
serde_json = "1.0.0"
toml = "0.4.0"
