[package]
authors = ["Jake Goulding <jake.goulding@integer32.com>"]
name = "top-crates"
version = "0.1.0"

[dependencies]
cargo = "0.20.0"
lazy_static = "0.2.8"
reqwest = "0.7.2"
serde = "1.0.1"
serde_derive = "1.0.1"
serde_json = "1.0.0"
toml = "0.4.0"
